// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bggaeemkonwbdqgrklzn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJnZ2FlZW1rb253YmRxZ3JrbHpuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5MTAzNDAsImV4cCI6MjA2OTQ4NjM0MH0.luEEVXZ8SOc2GPM0klkH7a8X-Zp-m_KCq5Pu74nNXpc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});